#!/bin/csh -f

# author gurjyan
# date 12.16.14

setenv PYTHONPATH $PXMSG_HOME\:$PXMSG_HOME/core\:$PXMSG_HOME/sys\:$PXMSG_HOME/sys/regdis\:$PXMSG_HOME/data\:$PXMSG_HOME/net

cd "$PXMSG_HOME/xsys"

if ( $1 == "-h" || $1 == "-help" ) then
    echo ""
    echo "Starts xMsg node (python binding)"
    echo "---------------------------------"
    echo "synopsis: px_node"
    echo ""
else
    python xMsgNode.py
endif
