#!/usr/bin/env bash
# author royarzun
# date 12.16.14


if ! $(python -c 'from xmsg.xsys.xMsgRegistrar import main' &> /dev/null);
then
    echo "Please check that you have xMsg and its dependencies installed in your system or virtual environment ";
else
    python -m 'from xmsg.xsys.xMsgRegistrar' ${@}
fi

