#!/usr/bin/env bash
# author royarzun


if ! $(python -c 'from xmsg.examples.Publisher import main' &> /dev/null); then
    echo "Please check that you have xMsg and its dependencies installed in your system or virtual environment ";
else
    python -m 'xmsg.examples.Publisher' ${@}
fi
